# Generated by Django 5.2.1 on 2025-05-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=100)),
                ('c_name', models.CharField(max_length=100)),
                ('c_video_blob', models.BinaryField(default=bytes)),
                ('c_video_file', models.FileField(upload_to='videos/')),
                ('c_uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categoryvideo',
            },
        ),
        migrations.DeleteModel(
            name='Category_video',
        ),
    ]
